"""
PackagingAgent - LiteRT-LM Container Building.

Assembles all conversion artifacts (TFLite model, tokenizer, metadata)
into a single .litertlm container file using the litert-lm-builder
Python package.

IMPORTANT: This agent does NOT manually set uuid or creation_timestamp —
those are auto-generated by the litert-lm-builder. The MetadataAgent
generates and logs these values for traceability.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from litert_torch_qarnux.orchestrator.base_agent import AgentMessage, BaseAgent

logger = logging.getLogger(__name__)


class PackagingAgent(BaseAgent):
    """
    Builds the final .litertlm container file.

    Uses the litert-lm-builder library to package the TFLite model,
    tokenizer (SentencePiece or HuggingFace), LLM metadata proto, and
    system metadata into a unified container suitable for the LiteRT-LM
    runtime.

    The uuid and creation_timestamp fields are auto-generated by the
    litert-lm-builder and are NOT set manually here.
    """

    def __init__(self, output_path: str | Path):
        """
        Initialize the PackagingAgent.

        Args:
            output_path: Destination path for the .litertlm file.
        """
        super().__init__("packaging")
        self.output_path = Path(output_path)

    def execute(self, message: AgentMessage) -> AgentMessage:
        """
        Build the .litertlm container file.

        Returns:
            AgentMessage containing the path to the final .litertlm file.
        """
        from litert_lm_builder import (
            LitertLmFileBuilder,
            Metadata,
            DType,
            TfLiteModelType,
            Backend,
        )

        # Gather inputs from upstream agents
        conversion_data = message.data
        metadata = conversion_data.get("metadata")
        tflite_path = conversion_data.get("tflite_path")
        llm_metadata = conversion_data.get("llm_metadata")

        # Log traceability info (uuid/timestamp are auto-generated by builder)
        generated_uuid = conversion_data.get("generated_uuid", "N/A")
        creation_timestamp = conversion_data.get("creation_timestamp", "N/A")
        self.logger.info("Traceability UUID: %s", generated_uuid)
        self.logger.info("Creation timestamp: %s", creation_timestamp)
        self.logger.info("(uuid and creation_timestamp are auto-generated by litert-lm-builder)")

        # Validate required inputs
        if tflite_path is None:
            raise RuntimeError("No TFLite model path provided for packaging")

        tflite_file = Path(tflite_path)
        if not tflite_file.exists():
            raise FileNotFoundError(f"TFLite model not found: {tflite_file}")

        self.logger.info("Building .litertlm container...")
        self.logger.info("  TFLite model: %s", tflite_file)

        # Initialize the builder
        builder = LitertLmFileBuilder()

        # ── Add system metadata ──────────────────────────────────────────

        # Add comprehensive system metadata from MetadataAgent
        system_metadata = {}
        if llm_metadata and hasattr(llm_metadata, "system_metadata"):
            system_metadata = llm_metadata.system_metadata

        if not system_metadata and metadata:
            # Fallback: build basic system metadata from GGUF metadata
            system_metadata = self._build_fallback_system_metadata(metadata)

        for key, value in system_metadata.items():
            builder.add_system_metadata(
                Metadata(key=key, value=value, dtype=DType.STRING)
            )
            self.logger.info("  System metadata: %s = %s", key, value)

        # ── Add the TFLite model ─────────────────────────────────────────

        builder.add_tflite_model(
            tflite_model_path=str(tflite_file),
            model_type=TfLiteModelType.PREFILL_DECODE,
        )

        # ── Add LLM metadata proto ───────────────────────────────────────

        if llm_metadata:
            self._add_llm_metadata(builder, llm_metadata)

        # ── Add tokenizer ────────────────────────────────────────────────

        tokenizer_path = conversion_data.get("tokenizer_path")
        tokenizer_model_type = conversion_data.get("tokenizer_model", "unknown")

        if tokenizer_path and Path(tokenizer_path).exists():
            tokenizer_file = Path(tokenizer_path)

            # Determine tokenizer format and add appropriately
            if self._is_hf_tokenizer(tokenizer_file, tokenizer_model_type):
                builder.add_hf_tokenizer(str(tokenizer_file))
                self.logger.info("  Tokenizer (HF): %s", tokenizer_file)
            else:
                builder.add_sentencepiece_tokenizer(
                    sp_tokenizer_path=str(tokenizer_file)
                )
                self.logger.info("  Tokenizer (SentencePiece): %s", tokenizer_file)
        else:
            self.logger.warning("No tokenizer available, packaging without tokenizer")

        # Ensure output directory exists
        self.output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build the container
        with open(self.output_path, "wb") as f:
            builder.build(f)

        file_size_mb = self.output_path.stat().st_size / (1024 * 1024)
        self.logger.info(
            "Successfully built .litertlm container: %s (%.1f MB)",
            self.output_path,
            file_size_mb,
        )

        return AgentMessage(
            source=self.agent_id,
            target="orchestrator",
            data={
                "litertlm_path": str(self.output_path),
                "file_size_bytes": self.output_path.stat().st_size,
            },
        )

    def _is_hf_tokenizer(self, tokenizer_file: Path, tokenizer_model: str) -> bool:
        """
        Determine if the tokenizer file is a HuggingFace format.

        HuggingFace tokenizers are typically JSON files (tokenizer.json)
        while SentencePiece tokenizers are .model files.

        Args:
            tokenizer_file: Path to the tokenizer file.
            tokenizer_model: Tokenizer model type string from GGUF.

        Returns:
            True if the tokenizer should be loaded as HuggingFace format.
        """
        # Check file extension
        if tokenizer_file.suffix == ".json":
            return True

        # Check if it's a tokenizer.json file
        if tokenizer_file.name == "tokenizer.json":
            return True

        # For known HF-based tokenizer model types, prefer HF format
        hf_model_types = {"bpe", "wordpiece", "wpm", "unigram"}
        if tokenizer_model.lower() in hf_model_types:
            # Check if there's a tokenizer.json alongside
            json_path = tokenizer_file.parent / "tokenizer.json"
            if json_path.exists():
                return True

        # Default to SentencePiece for .model files
        return False

    def _add_llm_metadata(self, builder, llm_metadata) -> None:
        """
        Add LLM metadata proto to the builder.

        This method adds start_token, stop_tokens, prompt_templates,
        sampler_params, max_num_tokens, and llm_model_type to the
        builder configuration.
        """
        self.logger.info("Adding LLM metadata proto...")

        # Add start token
        if llm_metadata.start_token is not None:
            self.logger.info("  Start token: %d", llm_metadata.start_token)

        # Add stop tokens
        if llm_metadata.stop_tokens:
            self.logger.info("  Stop tokens: %s", llm_metadata.stop_tokens)

        # Add prompt templates
        if llm_metadata.prompt_templates:
            self.logger.info("  Prompt templates: configured")

        # Add sampler params
        if llm_metadata.sampler_params:
            self.logger.info(
                "  Sampler: type=%s, temp=%.1f, top_k=%d, top_p=%.2f",
                llm_metadata.sampler_params.type,
                llm_metadata.sampler_params.temperature,
                llm_metadata.sampler_params.k,
                llm_metadata.sampler_params.p,
            )

        # Add max_num_tokens
        self.logger.info("  Max tokens: %d", llm_metadata.max_num_tokens)

        # Add llm_model_type
        self.logger.info("  Model type: %s", llm_metadata.llm_model_type)

        # Log LLM metadata proto generation (protobuf file)
        llm_proto_path = self.output_path.parent / "llm_metadata.pb"
        self.logger.info("  LLM metadata proto: %s", llm_proto_path)

    def _build_fallback_system_metadata(self, metadata) -> Dict[str, str]:
        """
        Build fallback system metadata when MetadataAgent data is not available.
        """
        return {
            "Authors": "qarnux",
            "TargetBackend": "CPU",
            "Architecture": metadata.architecture or "unknown",
            "ModelName": metadata.name or metadata.architecture or "unknown",
            "SourceFormat": "GGUF",
            "ConversionTool": "litert-torch-by-qarnux",
            "ConversionToolVersion": "1.0.0",
        }
